### ISSUE TITLE
playlist

### ISSUE THREAD

**Issue by eduzappa18** [Televito/TDT-Mundo#1]
Hola, llevo usando esta playlist desde hace tiempo

Por que se borró y ahora volvio como una versión mas mala con menos canales?
@Televito Volverás a publicar la lista antigua? o ya no la mantendrás mas?

Gracias

**Comment by kratoz29** [comment]
Hola @eduzappa18 , no obtuviste respuesta, o se te comunicó algo aparte sobre el destino de esta lista?

**Comment by eduzappa18** [comment]
@kratoz29 nada
no creo que Televito siga interesado en mantenerla otra vez

acá hay otra playlist gigante con canales de casi todos los paises por si te interesa https://github.com/iptv-org/iptv

**Comment by Televito** [comment]
Si la estoy manteniendo de nuevo, se me cayó la lista que tenía alojada en un host privado, así que volví por estos lados pero solo estoy incorporando señales mas estables que no tengan caídas frecuentes. Por motivos de trabajo no puedo dedicarle tanto tiempo como antes. Además el 04 de Abril se viene el apagón de la TV análoga en Chile por lo que los canales principales de Chile llegarán a la mayor parte del territorio a través de la TDT, esta lista solo será para tener algunos canales opcionales. Puedo agregar algunos de la antigua lista si  resultan de interés, pero la lista a como la tengo actualmente es mas o menos como se mantendrá.

**Comment by kratoz29** [comment]
> Si la estoy manteniendo de nuevo, se me cayó la lista que tenía alojada en un host privado, así que volví por estos lados pero solo estoy incorporando señales mas estables que no tengan caídas frecuentes. Por motivos de trabajo no puedo dedicarle tanto tiempo como antes. Además el 04 de Abril se viene el apagón de la TV análoga en Chile por lo que los canales principales de Chile llegarán a la mayor parte del territorio a través de la TDT, esta lista solo será para tener algunos canales opcionales. Puedo agregar algunos de la antigua lista si resultan de interés, pero la lista a como la tengo actualmente es mas o menos como se mantendrá.

Entiendo, muchas gracias por tu respuesta, siempre es bueno tener más alternativas para este tipo de proyectos!
