### ISSUE TITLE
Agregar canal

### ISSUE THREAD

**Issue by djgerman10** [Televito/TDT-Mundo#2]
pedido para agregar el canal 12 de misiones Argentina
[https://www.megatelevisionhd.com/en-vivo/doce-misiones/](https://www.megatelevisionhd.com/en-vivo/doce-misiones/)

si no me equivoco el link debería ser este https://vmf.edge-apps.net/embed/live.php?streamname=c12_live01-100129&autoplay=true

Muchas gracias Televito la lista de canales esta Super

**Comment by Televito** [comment]
Hay algo que evita incorporar esta señal. En navegador se visualiza pero en aplicaciones de IPTv no está funcionando.
